name: Deploy to dev Cloudflare Worker
on:
  workflow_dispatch:
  pull_request:
    branches:
      - stampy-redesign
    types:
      - closed
env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN_APRILLION_WORKERS_DEV }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
jobs:
  deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Clone stampy-ui repository code
        uses: actions/checkout@v3
      - name: Deploy to Cloudflare
        run: |
          cat wrangler.toml.template \
            | sed s/stampy-ui/redesign/ \
            | sed s/{CLOUDFLARE_ACCT_ID}/${{ secrets.CLOUDFLARE_ACCT_ID_APRILLION_WORKERS_DEV }}/ \
            | sed s/{STAMPY_KV_ID}/${{ secrets.STAMPY_KV_ID_APRILLION_WORKERS_DEV }}/ \
            | sed s/{CODA_TOKEN}/${{ secrets.CODA_TOKEN }}/ \
            | sed s/{CODA_INCOMING_TOKEN}/${{ secrets.CODA_INCOMING_TOKEN }}/ \
            | sed s/{CODA_WRITES_TOKEN}/${{ secrets.CODA_WRITES_TOKEN }}/ \
            | sed s/{MATOMO_DOMAIN}/${{ secrets.MATOMO_DOMAIN }}/ \
            | sed s/{DISCORD_LOGGING_CHANNEL_ID}/${{ secrets.DISCORD_LOGGING_CHANNEL_ID }}/ \
            | sed s/{DISCORD_LOGGING_TOKEN}/${{ secrets.DISCORD_LOGGING_TOKEN }}/ \
            | sed s/{EDITOR_USERNAME}/${{ secrets.EDITOR_USERNAME }}/ \
            | sed s/{EDITOR_PASSWORD}/${{ secrets.EDITOR_PASSWORD }}/ \
            | sed s,{SENTRY_DSN},${{ secrets.SENTRY_DSN }}, \
            > wrangler.toml
          npm ci
          npm run deploy
      - name: 'Debug: list files in build directory'
        run: ls -R build public/build
